### ISSUE TITLE
Enquiry for the reproducibility of this code

### ISSUE THREAD

**Issue by JiuFengSC** [kyegomez/NaViT#11]
Hi, Eternal Reclaimer!
Thank you very much for providing this code.

I also tried to reproduce the results in the NaViT paper by using lucidrains' code[[here](https://github.com/lucidrains/vit-pytorch/blob/main/vit_pytorch/na_vit.py)], but didn't get good results.

May I ask for those?
      - The training bash script
      - The reproduced results at your place.

Thanks again!

**Comment by mudassirkhan19** [comment]
Hi @JiuFengSC ,
Were you able to reproduce the results?
